[project]
name = "stdlib"
version = "0.0.1"
description = "Implement stdlib in pure python using ffis"
readme = "README.md"
license = { text = "MIT" }
requires-python = ">=3.9"

[tool.isort]
profile = "black"
