from typing import List, Optional

def compile_pattern(pattern: str) -> int: ...
def match_compiled(id: int, text: str) -> bool: ...
def release_compiled(id: int) -> None: ...
def match(pattern: str, text: str) -> bool: ...
def search_pattern(id: int, text: str) -> Optional[str]: ...
def findall_pattern(id: int, text: str) -> List[str]: ...
def free_matches(matches: List[str]) -> None: ...
def substitute_pattern(id: int, text: str, replacement: str) -> Optional[str]: ...
def free(ptr: object) -> None: ...
